name: Handle issues 
on: issues
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details 
        run: echo "Issue event triggered on ${{ toJSON(github.event)}}"
    